{{- if .Values.configMaps.initConf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lampac.fullname" . }}-init-conf
  labels:
    {{- include "lampac.labels" . | nindent 4 }}
data:
  init.conf: |
{{ .Values.configMaps.initConf.data | nindent 4 }}
---
{{- end }}
{{- if .Values.configMaps.manifest.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lampac.fullname" . }}-manifest
  labels:
    {{- include "lampac.labels" . | nindent 4 }}
data:
  manifest.json: |
    [
    {{- $first := true }}
    {{- range $key, $value := .Values.configMaps.manifest.data }}
    {{- if not $first }},{{ end }}
      {
        "enable": {{ $value.enable | default false }},
        "dll": {{ $value.dll | default (printf "%s.dll" $key) | quote }}{{- $defaultInitspace := "" }}{{- if eq $key "JacRed" }}{{- $defaultInitspace = "Jackett.ModInit" }}{{- else if eq $key "Tracks" }}{{- $defaultInitspace = "Tracks.ModInit" }}{{- else if eq $key "TorrServer" }}{{- $defaultInitspace = "TorrServer.ModInit" }}{{- else if eq $key "Lamson" }}{{- $defaultInitspace = "Lamson.ModInit" }}{{- else if eq $key "Kinogram" }}{{- $defaultInitspace = "Lamson.ModInit" }}{{- end }}{{- if or $value.initspace $defaultInitspace }},
        "initspace": {{ $value.initspace | default $defaultInitspace | quote }}{{- end }}
        {{- if $value.middlewares }},
        "middlewares": {{ $value.middlewares | quote }}
        {{- end }}
        {{- if $value.online }},
        "online": {{ $value.online | quote }}
        {{- end }}
        {{- if $value.sisi }},
        "sisi": {{ $value.sisi | quote }}
        {{- end }}
        {{- if $value.jac }},
        "jac": [
        {{- $jacFirst := true }}
        {{- range $value.jac }}
        {{- if not $jacFirst }},{{ end }}
          {
            "enable": {{ .enable | default false }},
            "namespace": {{ .namespace | quote }}
          }
        {{- $jacFirst = false }}
        {{- end }}
        ]
        {{- end }}
      }
    {{- $first = false }}
    {{- end }}
    ]
{{- end }}